export const professors = [
    {
        id: 'so',
        name: 'Sistemas Operacionais',
        shortName: 'Sistemas Operacionais',
        subject: 'Threads, Processos & Kernel',
        quote: '"Todo programa é um processo esperando a sua vez."',
        ultimateName: 'KERNEL PANIC (TELA AZUL)',
        ultimateQuote: '"Processo encerrado com código de erro fatal."',
        color: '#ef4444',
        idleKey: 'prof_so_idle',
        portraitKey: 'prof_so_portrait',
        idleUrl: '/assets/professors/so_idle.png',
        portraitUrl: '/assets/professors/so_portrait.png',
        atlasKey: 'atlas_so',
        atlasImage: '/assets/so/phaser/SO.png',
        atlasJson: '/assets/so/phaser/SO.json',
        scale: 0.65
    },
    {
        id: 'eng_soft',
        name: 'Engenharia de Software',
        shortName: 'Eng. de Software',
        subject: 'Scrum, Requisitos & Clean Code',
        quote: '"Todo bug caro começou como um requisito mal entendido."',
        ultimateName: 'DEPLOY EM PRODUÇÃO NA SEXTA',
        ultimateQuote: '"Rollback impossível. Sistema quebrado."',
        color: '#10b981',
        idleKey: 'prof_eng_soft_idle',
        portraitKey: 'prof_eng_soft_portrait',
        idleUrl: '/assets/professors/eng_soft_idle.png',
        portraitUrl: '/assets/professors/eng_soft_portrait.png',
        atlasKey: 'atlas_eng_soft',
        atlasImage: '/assets/eng/phaser/eng.png',
        atlasJson: '/assets/eng/phaser/eng.json',
        scale: 0.65
    },
    {
        id: 'poo',
        name: 'Programação Orientada a Objetos',
        shortName: 'Programação OO',
        subject: 'Classes, Polimorfismo & Herança',
        quote: '"Tudo é objeto. Até o problema."',
        ultimateName: 'NULL POINTER EXCEPTION',
        ultimateQuote: '"Tentativa ilegal de acessar referência nula."',
        color: '#84cc16',
        idleKey: 'prof_poo_idle',
        portraitKey: 'prof_poo_portrait',
        idleUrl: '/assets/professors/poo_idle.png',
        portraitUrl: '/assets/professors/poo_portrait.png',
        atlasKey: 'atlas_poo',
        atlasImage: '/assets/poo/phaser/poo.png',
        atlasJson: '/assets/poo/phaser/poo.json',
        scale: 0.65
    },
    {
        id: 'web',
        name: 'Web & Mobile',
        shortName: 'Web & Mobile',
        subject: 'Frontend, Fullstack & APIs',
        quote: '"Bom código funciona em qualquer tela."',
        ultimateName: '404 NOT FOUND (CORS ERROR)',
        ultimateQuote: '"Recurso permanentemente inacessível."',
        color: '#3b82f6',
        idleKey: 'prof_web_idle',
        portraitKey: 'prof_web_portrait',
        idleUrl: '/assets/professors/web_idle.png',
        portraitUrl: '/assets/professors/web_portrait.png',
        atlasKey: 'atlas_web',
        atlasImage: '/assets/web/phaser/web.png',
        atlasJson: '/assets/web/phaser/web.json',
        scale: 0.65
    },
    {
        id: 'bd',
        name: 'Banco de Dados',
        shortName: 'Banco de Dados',
        subject: 'SQL, Índices & Normalização',
        quote: '"Dado bem organizado vale mais que ouro."',
        ultimateName: 'DROP DATABASE --FORCE',
        ultimateQuote: '"Seus dados foram purgados do servidor."',
        color: '#a855f7',
        idleKey: 'prof_bd_idle',
        portraitKey: 'prof_bd_portrait',
        idleUrl: '/assets/professors/bd_idle.png',
        portraitUrl: '/assets/professors/bd_portrait.png',
        atlasKey: 'atlas_bd',
        atlasImage: '/assets/bd/phaser/bd.png',
        atlasJson: '/assets/bd/phaser/bd.json',
        scale: 0.728, // Calibrado para ter a mesma altura do Eng. de Software (345 * 0.65 = 224.25px vs 308 * 0.728 = 224.22px)
        portraitScale: 1.12,
        portraitOffsetY: -1
    },
    {
        id: 'redes',
        name: 'Redes de Computadores',
        shortName: 'Redes',
        subject: 'TCP/IP, Roteamento & Ping',
        quote: '"Toda conexão começa com um bom ping."',
        ultimateName: 'DDoS OVERLOAD (PING DA MORTE)',
        ultimateQuote: '"Tempo limite de resposta esgotado."',
        color: '#f59e0b',
        idleKey: 'prof_redes_idle',
        portraitKey: 'prof_redes_portrait',
        idleUrl: '/assets/professors/redes_idle.png',
        portraitUrl: '/assets/professors/redes_portrait.png',
        atlasKey: 'atlas_redes',
        atlasImage: '/assets/redes/phaser/redes.png',
        atlasJson: '/assets/redes/phaser/redes.json',
        scale: 0.65
    }
];

export function getProfessorById(id) {
    return professors.find(p => p.id === id) || professors[0];
}
